package by.salary.serviceinvitation.filters;

public enum PermissionsEnum {
    ALL_PERMISSIONS,

    //ADMINISTRATOR
    REDACT_ORGANISATION_INFO,
    GRANT_ORGANISATION,
    PROMOTE_USER,
    DEMOTE_USER,

    //MODERATOR
    INVITE_USER,
    EXPIRE_USER,

    READ_USER_AGREEMENT,
    ADD_USER_AGREEMENT,
    DELETE_USER_AGREEMENT,
    CHANGE_USER_AGREEMENT,

    CREATE_AGREEMENT_LIST,
    UPDATE_AGREEMENT_LIST,
    DELETE_AGREEMENT_LIST,

    CREATE_AGREEMENT_STATE,
    UPDATE_AGREEMENT_STATE,
    DELETE_AGREEMENT_STATE,

    //USER
    READ_AGREEMENT,
    READ_OWN_AGREEMENT_STATES
}
