eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ### Test Service route
      - id: api-gateway
        uri: lb://api-service
        predicates:
          - Path=/test
        filters:
          - AuthenticationFilter
        ### User Service route
      - id: service-user
        uri: lb://service-user
        predicates:
          - Path=/users/**
        filters:
          - AuthenticationFilter
          - LoggingFilter
        ### User auth Service route
      - id: service-user-auth
        uri: lb://service-user
        predicates:
          - Path=/account/**
        filters:
          - AuthenticationFilter
          - LoggingFilter
        ### Identity Server route
      - id: identity-service
        uri: lb://identity-server
        predicates:
          - Path=/auth/**, /oauth2/**
        ### Invitation Service route
      - id: service-invitation
        uri: lb://service-invitation
        predicates:
          - Path=/invitations/**
        ### User agreement Service route
      - id: service-agreement
        uri: lb://service-agreement
        predicates:
          - Path=/agreements/**
        ### User Service route
      - id: service-user-organisation
        uri: lb://service-user
        predicates:
          - Path=/organisations/**
        ### User agreement Service route
      - id: service-user-user-agreement
        uri: lb://service-user
        predicates:
          - Path=/useragreements/**
        ### Mail Service route
      - id: service-mail
        uri: lb://service-mail
        predicates:
          - Path=/mail/**
server:
  port: 8080
