package by.salary.serviceuser.entities;


public enum PermissionsEnum {
    ALL_PERMISSIONS,

    //ADMINISTRATOR
    REDACT_ORGANISATION_INFO,
    GRANT_ORGANISATION,
    PROMOTE_USER,
    DEMOTE_USER,

    //MODERATOR
    INVITE_USER,
    EXPIRE_USER,

    READ_USER_AGREEMENT,
    CRUD_USER_AGREEMENT,

    READ_ALL_USERS,

    CRUD_AGREEMENT_LIST,

    CRUD_AGREEMENT_STATE,

    //USER
    READ_AGREEMENT,
    AUTHORITY_REDACTION,
    READ_OWN_AGREEMENT_STATES
}
