package by.salary.serviceuser.entities;


public enum PermissionsEnum {
    ALL_PERMISSIONS,

    //ADMINISTRATOR
    REDACT_ORGANISATION_INFO,
    PROMOTE_USER,
    DEMOTE_USER,

    //MODERATOR
    INVITE_USER,
    EXPIRE_USER,

    CRUD_USER_AGREEMENT,

    CRUD_AGREEMENT_LIST,

    CRUD_AGREEMENT_STATE,
    //USER

    READ_ALL_USERS,
    REDACT_USER_INFO,
    AUTHORITY_REDACTION
}
